name: CI

# Specify which GitHub events will trigger CI build
on: push

#Define a single job, build
jobs:

  build:

    # Specify the OS of the runner
    runs-on: ubuntu-latest

    # Define our steps
    steps:

      # Firstly check out the repo
      - name: Checkout respository
        uses: actions/checkout@v2
    
      # Set up Python env
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
    
      # Install dependencies
      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements
          pip install -e .
      
      # Run our tests
      - name: Test with PyTest
        run: |
          pytest --cov=inflammation.models tests/text_models.py